=== ChrisClark13/artificing/resources/mods/Artificing/guidebooks/guideBookSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:attributeGroup name="coords">
		<xsd:attribute name="y" type="xsd:int" use="required" />
		<xsd:attribute name="x" type="xsd:int" use="required" />
	</xsd:attributeGroup>

	<xsd:group name="formattingTags">
		<xsd:choice>
			<xsd:element name="black">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="darkBlue">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="darkGreen">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="darkAqua">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="darkRed">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="purple">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="gold">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="gray">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="darkGray">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="blue">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="green">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="aqua">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="red">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="lightPurple">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="yellow">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="white">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="random">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="bold">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="strikethrough">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="underline">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="italic">
				<xsd:complexType />
			</xsd:element>
			<xsd:element name="reset">
				<xsd:complexType />
			</xsd:element>
		</xsd:choice>
	</xsd:group>

	<xsd:group name="pageContentTypes">
		<xsd:choice>
			<xsd:element name="text">
				<xsd:complexType mixed="true">
					<xsd:group ref="formattingTags" minOccurs="0" maxOccurs="unbounded" />
					<xsd:attributeGroup ref="coords" />
					<xsd:attribute name="lineWidth" type="xsd:positiveInteger" use="optional" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="image">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attributeGroup ref="coords" />
							<xsd:attribute name="width" type="xsd:positiveInteger" use="required" />
							<xsd:attribute name="height" type="xsd:positiveInteger" use="required" />
							<xsd:attribute name="imageWidth" type="xsd:positiveInteger" use="optional" />
							<xsd:attribute name="imageHeight" type="xsd:positiveInteger" use="optional" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="craftingRecipe">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attributeGroup ref="coords" />
							<xsd:attribute name="size"
                                use="required">
								<xsd:simpleType>
									<xsd:restriction base="xsd:positiveInteger">
										<xsd:enumeration
                                            value="2" />
										<xsd:enumeration
                                            value="3" />
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:attribute>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="itemStack">
				<xsd:complexType>
					<xsd:choice minOccurs="0" maxOccurs="1">
						<xsd:element name="enchantment"
                            maxOccurs="1">
							<xsd:complexType>
								<xsd:attribute name="name" use="required" />
								<xsd:attribute name="level"
                                    use="optional">
									<xsd:simpleType>
										<xsd:restriction
                                            base="xsd:int">
											<xsd:minInclusive
                                                value="1" />
											<xsd:maxInclusive
                                                value="10" />
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:attribute>
							</xsd:complexType>
						</xsd:element>
					</xsd:choice>
					<xsd:attributeGroup ref="coords" />
					<xsd:attribute name="name" type="xsd:string" use="required" />
					<xsd:attribute name="metadata" type="xsd:positiveInteger" use="optional" />
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
	</xsd:group>

	<xsd:element name="book">
		<xsd:complexType>
			<xsd:sequence>
                <xsd:element name ="section" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="page" minOccurs="1" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:group ref="pageContentTypes"/ minOccurs="0" maxOccurs="unbounded">
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="name" type="xsd:string" use="required"/>
                        <xsd:attribute name="hasBookmark" type="xsd:boolean" use="optional"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== ChrisClark13/artificing/resources/mods/Artificing/guidebooks/startingBook.xml
<?xml version="1.0" encoding="UTF-8"?>

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="guideBookSchema.xsd">
    <section name="Table of Contents" hasBookmark="true" bookmarkColor="CC0000">
        <page>
            <text x="0" y="10" alignment="center">Fake publishing info here</text>
        </page>
        <page>
            <image x="8" y="0" width="100" height = "50">/mods/Artificing/guidebooks/tomeOfArtificing.png</image>
<text x="0" y="53" alignment="center">Table of Contents
here eventually</text>
        </page>
    </section>
    <section name="Artificing Table" hasBookmark="true" bookmarkColor="00CC00">
        <page>
            <text x="0" y="3" alignment="center">The Artificing Table</text>
<text x="3" y="20">    This table is the center of your Artificing workspace. It lets you pick and choose the enchantments you want and place them on your item.

    It even lets you make super-powered enchantments! (Though it costs an arm and a leg in levels to do that.)</text>
        </page>
        <page/>
    </section>
    <section name="TEST SECTION" hasBookmark="true" bookmarkColor="0000CC">
        <page/>
        <page>
            <text x="0" y="3" lineWidth="113" alignment="right">Testing!</text>
        </page>
    </section>
</book>

=== ChrisClark13/artificing/src/main/resources/assets/artificing/guidebooks/startingBook.xml
<?xml version="1.0" encoding="UTF-8"?>

<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="guideBookSchema.xsd">
    <section name="Table of Contents" hasBookmark="true" bookmarkColor="CC0000">
        <page>
            <text x="0" y="10" alignment="center">Magki Books.
Published by Magki Books.
Copyright reserved. 
4th wall street, block road, block city, Blocksville (MC).
First published on 1276.
Copy 1020102393.
Author: Cyntain (I)

</text>
        </page>
        <page>
            <image x="8" y="0" width="100" height = "50">guidebooks/tomeOfArtificing.png</image>
<text x="0" y="53" alignment="center">-- Contents --
Artificing and Knowledge: P.2
Research Table discovery: P.6
After-thought: Disenchanter: P.12 </text>
        </page>
    </section>
    <section name="Artificing Table" hasBookmark="true" bookmarkColor="00CC00">
        <page>
            <text x="0" y="3" alignment="center">The Artificing Table</text>
		<text x="3" y="17">This table, is one of the most powerful tables in your collection. With your past knowledge of basic infusing, you are able to create powerful enchantments. 
 Although be warned this magic does come at a price. A vast amount of EXP is used in-order to infuse a rune with an item. The more runes you intend on infusing the greater the price you will pay.  </text>
        </page>
	
        <page>
		<text x="0" y="5" alignment="center">-- Construction --</text>
			<image x="32" y="15" width="50" height = "50">textures/gui/crafting.png</image>
	</page>
 	<page>
		<text x="2" y="3"> You should consider that the table doesn't have multiple uses, if you run out of symbols you can not use the table anymore. 
But never fear you can regain these symbols, you can use runes to regain symbols. Each level of rune gives back 3 symbols, EX:level 3 rune gives back 9 symbols.To use the runes on the table you must shift right click on the table, and you will notice that the symbols will reappear again.</text>
	</page>
	<page/>
	<page/>
    </section>
    <section name="Research Table" hasBookmark="true" bookmarkColor="F7D439">
        <page/>
        <page>
            <text x="0" y="3" lineWidth="113" alignment="right">Testing!</text>
        </page>
        <page/>       
        <page/>
        <page/>
    </section>
    <section name="Disenchanter" hasBookmark="true" bookmarkColor="8521FF">
        <page>
            <text x="0" y="10" alignment="center">Just some more testing!</text>
        </page>
        <page/>
        <page/>     
        <page>
            <text x="0" y="50" alignment="center">That's all folks!</text>
        </page>
    </section>
</book>
